project_id = "lhbowpbcpwoiparwnwgt"

[api]
port = 56311
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 57322
shadow_port = 57323
major_version = 17

[studio]
port = 55313

[inbucket]
port = 55314

[storage]
file_size_limit = 52428800

[analytics]
port = 55317

[auth]
site_url = "https://easymo.vercel.app"
additional_redirect_urls = [
  "https://easymo.vercel.app",
  "https://easymo-git-main.vercel.app",
  "https://easymo-git-phase2-setup.vercel.app",
  "http://localhost:5173",
  "http://localhost:8080"
]
jwt_expiry = 3600
