steps:
  # Build the Docker image for Next.js admin-app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/easymo-admin-app', '.']
  
  # Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/easymo-admin-app']
  
  # Deploy to Cloud Run with environment variables from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'easymo-admin-app'
      - '--image=gcr.io/$PROJECT_ID/easymo-admin-app'
      - '--region=us-central1'
      - '--platform=managed'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=300'
      # Public environment variables (safe for client-side)
      - '--set-env-vars=NEXT_PUBLIC_SUPABASE_URL=${_SUPABASE_URL}'
      - '--set-env-vars=NEXT_PUBLIC_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}'
      # Server-side secrets from Secret Manager
      - '--update-secrets=SUPABASE_SERVICE_ROLE_KEY=supabase-service-role:latest'
      - '--update-secrets=EASYMO_ADMIN_TOKEN=easymo-admin-token:latest'
      - '--update-secrets=ADMIN_SESSION_SECRET=admin-session-secret:latest'
      # Optional: Configure for internal-only access (remove for public)
      # - '--no-allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/easymo-admin-app'

# Substitution variables (set via gcloud builds submit --substitutions)
substitutions:
  _SUPABASE_URL: 'https://your-project.supabase.co'
  _SUPABASE_ANON_KEY: 'your-anon-key-here'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'  # 30 minutes for monorepo build
