#!/bin/bash
# Deploy Mobility Migration via Supabase Dashboard

echo "========================================"
echo "Mobility Migration Deployment Guide"
echo "========================================"
echo ""
echo "The migration is ready to deploy. Please follow these steps:"
echo ""
echo "1. Go to Supabase Dashboard:"
echo "   https://supabase.com/dashboard/project/lhbowpbcpwoiparwnwgt/sql/new"
echo ""
echo "2. Copy and paste the SQL from this file:"
echo "   /tmp/apply_mobility_fix.sql"
echo ""
echo "3. Click 'Run' to execute"
echo ""
echo "Or run this command if you have psql and DATABASE_URL:"
echo "   psql \$DATABASE_URL < /tmp/apply_mobility_fix.sql"
echo ""
echo "Migration file location: /tmp/apply_mobility_fix.sql"
echo ""
echo "This migration will:"
echo "  ✓ Fix match_drivers_for_trip_v2 (error 42703)"
echo "  ✓ Fix match_passengers_for_trip_v2"
echo "  ✓ Add calculate_distance_km helper"
echo "  ✓ Create spatial indexes"
echo "  ✓ Grant permissions"
echo ""
