services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'

  coturn:
    image: instrumentisto/coturn
    restart: unless-stopped
    network_mode: host
    environment:
      - LT_cred_mech=true
    command:
      [
        "sh",
        "-c",
        "-n --min-port=49152 --max-port=65535 --fingerprint --lt-cred-mech --realm=example.com --user=${TURN_USERNAME:-turnuser}:${TURN_PASSWORD:-turnpass} --listening-port=3478 --external-ip=$(curl -s ifconfig.me)",
      ]
