packages:
  - services/*
  - packages/*
  - admin-app
  # - admin-app-v2  # DEPRECATED: Removed 2025-11-27
  - ai
  - waiter-pwa
  - real-estate-pwa
  - client-pwa

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd
