packages:
  - services/*
  - packages/*
  - admin-app
  - ai
  - waiter-pwa

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd
