packages:
  - services/*
  - packages/*
  - admin-app
  - ai
  - client-pwa

# NOTE: The following apps exist but are not in the workspace:
# - bar-manager-app: Uses workspace packages but requires lockfile update to add (run `pnpm install` without `--frozen-lockfile`)
# - backend: Python/infrastructure directory, not a Node.js package

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd
