packages:
  # Core shared packages
  - packages/*
  
  # Microservices
  - services/*
  
  # Admin panel (single unified admin)
  - admin-app
  
  # AI services
  - ai

# NOTE: The following directories exist but are not in the workspace:
# - bar-manager-production: Standalone production app (not managed by pnpm workspace)
# - backend: Python/infrastructure directory, not a Node.js package
# - .archive/deprecated-apps/bar-manager-app: Archived Dec 9, 2025

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd
