name: Monorepo quality gate

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'dashboards/**'
      - 'infra/ci/**'
      - '.github/**'

permissions:
  contents: read
  id-token: write
  checks: write

concurrency:
  group: monorepo-quality-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: agent_core
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/agent_core
      NODE_OPTIONS: --max_old_space_size=4096

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prime turbo cache (if present)
        run: pnpm dlx turbo prune --scope="@easymo/*" || echo "No turbo workspace"

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm type-check

      - name: Unit tests
        run: pnpm test -- --runInBand

      - name: Deno unit tests (Supabase functions)
        run: pnpm test:functions

      - name: Build packages and apps
        run: pnpm build

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monorepo-quality-logs
          path: |
            coverage/**
            **/junit.xml
          if-no-files-found: ignore
