name: Supabase Drift Check

on:
  pull_request:
    branches:
      - main
    paths:
      - 'supabase/**'
      - '.github/workflows/**'
      - 'infra/ci/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  drift-check:
    name: Validate Supabase migrations
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PREVIEW_DATABASE_URL: ${{ secrets.SUPABASE_PREVIEW_DATABASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: env.SUPABASE_ACCESS_TOKEN != ''

      - name: Ensure Supabase credentials are configured
        run: |
          if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
            echo "Supabase secrets are not configured. Set SUPABASE_ACCESS_TOKEN and SUPABASE_DB_PASSWORD to enable drift checks." >> "$GITHUB_STEP_SUMMARY"
            exit 0
          fi
        shell: bash

      - name: Set up pnpm
        if: env.SUPABASE_ACCESS_TOKEN != ''
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js
        if: env.SUPABASE_ACCESS_TOKEN != ''
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Supabase CLI dependencies
        if: env.SUPABASE_ACCESS_TOKEN != ''
        run: pnpm install --frozen-lockfile

      - name: Set up Supabase CLI
        if: env.SUPABASE_ACCESS_TOKEN != ''
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase project
        if: env.SUPABASE_ACCESS_TOKEN != ''
        working-directory: supabase
        run: |
          PROJECT_REF=$(awk -F'"' '/project_id/ {print $2}' config.toml)
          supabase link --project-ref "$PROJECT_REF" --access-token "$SUPABASE_ACCESS_TOKEN"

      - name: Run migration status
        if: env.SUPABASE_ACCESS_TOKEN != ''
        working-directory: supabase
        run: |
          supabase db status --env preview

      - name: Check for schema drift
        if: env.SUPABASE_ACCESS_TOKEN != ''
        working-directory: supabase
        run: |
          supabase db diff --linked --use-migra --schema public --file .tmp-schema-diff.sql
          if [ -s .tmp-schema-diff.sql ]; then
            echo "Detected schema drift between committed migrations and linked database" >&2
            cat .tmp-schema-diff.sql >&2
            exit 1
          fi

      - name: Cleanup temporary diff artifact
        if: env.SUPABASE_ACCESS_TOKEN != ''
        working-directory: supabase
        run: rm -f .tmp-schema-diff.sql
