-- Bars Data Migration - Batch 2 of 4 (Records 101-200)
-- Generated: 2025-11-12

BEGIN;

INSERT INTO public.bars (name, location_text, country, city_area, currency, slug) VALUES
('Woodhut Pub & Diner', '283 Tourist St, Qawra SPB 1022, Malta', 'Malta', 'Qawra', 'EUR', 'woodhut-pub-diner'),
('Tico Tico', '61 Strait St, Valletta, Malta', 'Malta', 'Valletta', 'EUR', 'tico-tico'),
('Bus Stop Lounge', 'St. George''s Road, St. Julian''s, Malta', 'Malta', 'St. Julian''s', 'EUR', 'bus-stop-lounge-3'),
('Felice Brasserie', NULL, 'Malta', NULL, 'EUR', 'felice-brasserie-2'),
('Spinola Cafe Lounge St Julians', 'Spinola Bay, St. Julian''s, Malta', 'Malta', 'St. Julian''s', 'EUR', 'spinola-cafe-lounge-st-julians'),
('Gandhi Tandoori', 'Mosta Road, St Paul''s Bay, Malta', 'Malta', 'St Paul''s Bay', 'EUR', 'gandhi-tandoori'),
('Aqualuna Lido', NULL, 'Malta', NULL, 'EUR', 'aqualuna-lido-2'),
('Compass Lounge', 'Triq It - Torri Tower road, 1000, Sliema, Malta', 'Malta', 'Sliema', 'EUR', 'compass-lounge'),
('Maison Noire Bar & Restaurant', '24F3+WMV, KK 15 Rd, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'maison-noire-bar-restaurant'),
('Gorillas Golf Hotel', 'KG 274 St, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'gorillas-golf-hotel'),
('Juru Garden Bar', 'Juru, Rwanda', 'Malta', 'Kigali', 'EUR', 'juru-garden-bar'),
('Ubumwe Grande Hotel Kigali', 'KN 67 St, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'ubumwe-grande-hotel-kigali'),
('Billy''s Bistro & Bar', '9 KG 13 Ave, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'billys-bistro-bar'),
('The Crafty Cat Pub', 'George Borg Oliver, Mall, Tower Road, St Julian''s, Malta', 'Malta', 'St Julian''s', 'EUR', 'the-crafty-cat-pub'),
('Wok to Walk', 'St George''s Road, St Julian''s, Malta', 'Malta', 'St Julian''s', 'EUR', 'wok-to-walk'),
('Angela''s Valletta', '84 Triq San Gwann, Il-Belt Valletta, Malta', 'Malta', 'Valletta', 'EUR', 'angelas-valletta'),
('The Dubliner', 'George Borg Olivier St, St Julian''s, Malta', 'Malta', 'St Julian''s', 'EUR', 'the-dubliner'),
('Zion Bar & Restaurant', 'St Thomas Bay, Marsaskala, Malta', 'Malta', 'Marsaskala', 'EUR', 'zion-bar-restaurant'),
('Plus 250', 'Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'plus-250'),
('East 24 Bar & Grill', 'KK 315 St, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'east-24-bar-grill'),
('Torino Bar & Restaurant', '23G3+CFP, KN 168 St, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'torino-bar-restaurant'),
('Ħelu Manna Gluten Free Kafeterija Valletta', '51 St. John''s Street, Valletta, Malta', 'Malta', 'Valletta', 'EUR', 'helu-manna-gluten-free-kafeterija-valletta'),
('AKI', '175 Strait St Corner of St. Street and Santa Lucia St Valletta, Valletta VLT 1455, Malta', 'Malta', 'Valletta', 'EUR', 'aki'),
('Pili Pili', '12 KG 303 St, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'pili-pili'),
('Piatto Nero Mediterranean Restaurant', 'Ramla Bay Resort, Triq Ir-Ramla, Il-Mellieħa MLH 7100, Malta', 'Malta', 'Mellieħa', 'EUR', 'piatto-nero-mediterranean-restaurant'),
('Kari-Beau Restaurant', 'KK 368 St, 2A, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'kari-beau-restaurant'),
('67 Kapitali', '67 Triq l-Ifran Il-Belt Valletta, Valletta VLT 1427, Malta', 'Malta', 'Valletta', 'EUR', '67-kapitali'),
('Singita Restaurant', 'ghajn tuffieha bay, Mġarr MGR 2093, Malta', 'Malta', 'Mġarr', 'EUR', 'singita-restaurant'),
('Lady Di', '21 Hughes Hallet, Tas-Sliema, Malta', 'Malta', 'Tas-Sliema', 'EUR', 'lady-di'),
('The Dragon Chinese restaurant', 'Nawfragju, Valletta, Malta', 'Malta', 'Valletta', 'EUR', 'the-dragon-chinese-restaurant'),
('Emerald Café and Restaurant', '70 KG 13 Ave, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'emerald-cafe-and-restaurant'),
('Medasia Fusion Lounge', NULL, 'Malta', NULL, 'EUR', 'medasia-fusion-lounge-2'),
('Cafe Society', '13 Triq San Gwann, Il-Belt Valletta, Malta', 'Malta', 'Valletta', 'EUR', 'cafe-society'),
('Vecchia Napoli Qawra', 'Dawret Il - Qawra, Qawra, Malta', 'Malta', 'Qawra', 'EUR', 'vecchia-napoli-qawra'),
('Tigne Beach Club', 'Tigné Seafront, Tas-Sliema SLM 3112, Malta', 'Malta', 'Tas-Sliema', 'EUR', 'tigne-beach-club'),
('Lino Kiosk', 'St Paul''s Bay, Malta', 'Malta', 'St Paul''s Bay', 'EUR', 'lino-kiosk'),
('Jungle Joy Bar - Restaurant', 'Triq il-Gzira, Il-Gżira, Malta', 'Malta', 'Gżira', 'EUR', 'jungle-joy-bar-restaurant'),
('King''s Gate Gastropub', 'Triq Tal-Hriereb L-Imsida, Msida MSD 1672, Malta', 'Malta', 'Msida', 'EUR', 'kings-gate-gastropub'),
('AFTER PARTY BAR & GRILL', 'KN 224 St, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'after-party-bar-grill'),
('Ivy House', 'Triq Tunis, Pembroke, Malta', 'Malta', 'Pembroke', 'EUR', 'ivy-house'),
('NAAR Restobar', '1 Triq Censu Tabone, St Julian''s STJ 1017, Malta', 'Malta', 'St Julian''s', 'EUR', 'naar-restobar'),
('Mason''s Cafe', 'WG74+9QP, Triq it Torri, Tas-Sliema, Malta', 'Malta', 'Tas-Sliema', 'EUR', 'masons-cafe'),
('The Manor Hotel', '64 KG 552 St, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'the-manor-hotel'),
('Fresco''s', 'Fresco''s Restaurant, Tower Road, Sliema SLM 1600, Malta', 'Malta', 'Sliema', 'EUR', 'frescos'),
('Hammett''s Mestizo', '11, Triq Schreiber San Giljan, St Julian''s STJ 3081, Malta', 'Malta', 'St Julian''s', 'EUR', 'hammetts-mestizo'),
('Fortizza', NULL, 'Malta', NULL, 'EUR', 'fortizza'),
('Zion Reggae Bar', 'Triq Paceville, St. Julian''s, Malta', 'Malta', 'St. Julian''s', 'EUR', 'zion-reggae-bar'),
('Victoria Gastro Pub', 'Triq il-Kbira, Valletta, Malta', 'Malta', 'Valletta', 'EUR', 'victoria-gastro-pub-2'),
('MedAsia Playa', 'Ix - Xatt Ta'' Qui - Si - Sana, Tas-Sliema, Malta', 'Malta', 'Tas-Sliema', 'EUR', 'medasia-playa'),
('The Road Devil Sea Front', 'WG64+WQM, Tower Road, Sliema SLM 1605, Malta', 'Malta', 'Sliema', 'EUR', 'the-road-devil-sea-front'),
('Kings Gate', NULL, 'Malta', NULL, 'EUR', 'kings-gate'),
('Uncles Restaurant', 'KK 21 Ave, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'uncles-restaurant'),
('THE EVEREST /NEPALESE & INDIAN RESTAURANT', 'SUQ TAL BELT, Is-Suq Tal-Belt - Valletta Food Market, Triq Il-Merkanti, Il-Belt Valletta VLT 1175, Malta', 'Malta', 'Valletta', 'EUR', 'the-everest-nepalese-indian-restaurant'),
('The Black Pearl', 'ix-Xatt Ta'' Xbiex, Ta'' Xbiex XBX 1028, Malta', 'Malta', 'Ta'' Xbiex', 'EUR', 'the-black-pearl'),
('Mamma Mia', 'Spinola Bay, St. Julian''s, Malta', 'Malta', 'St. Julian''s', 'EUR', 'mamma-mia'),
('Quelque Part Resto Bar', 'Rubangura House 5230, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'quelque-part-resto-bar'),
('Bistro 516', NULL, 'Malta', NULL, 'EUR', 'bistro-516'),
('Ten to Two Bar Resto', 'KN 203 St, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'ten-to-two-bar-resto'),
('Click Bar', 'Kk 18 st, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'click-bar'),
('Chez John Restaurant', 'KN 50 St, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'chez-john-restaurant'),
('The Londoner Pub Sliema', '83, The Strand Sliema, Sliema SLM 1022, Malta', 'Malta', 'Sliema', 'EUR', 'the-londoner-pub-sliema'),
('Carpe Diem Bistro', 'KK 374 St, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'carpe-diem-bistro'),
('¡LA LUZ!', '139 Tower Road, Sliema SLM 1604, Malta', 'Malta', 'Sliema', 'EUR', 'la-luz'),
('Munchies Mellieha Bay', 'Triq il-Marfa, Ghadira, Il-Mellieħa, Malta', 'Malta', 'Mellieħa', 'EUR', 'munchies-mellieha-bay'),
('Bodega and Brew Kacyiru', 'KG 545 St, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'bodega-and-brew-kacyiru'),
('Cafe Cuba St Julians', NULL, 'Malta', NULL, 'EUR', 'cafe-cuba-st-julians-2'),
('Bayview Seafood House', 'Dragonara Road - STJ 06 Triq Dragunara, San Ġiljan STJ 3141, Malta', 'Malta', 'San Ġiljan', 'EUR', 'bayview-seafood-house'),
('White Bridge', '90 Republic St, Valletta, Malta', 'Malta', 'Valletta', 'EUR', 'white-bridge'),
('Giuseppi''s Bar & Bistro', 'Salini Resort, Salina Bay, In-Naxxar, Malta', 'Malta', 'Naxxar', 'EUR', 'giuseppis-bar-bistro'),
('Il-Gabbana', 'Tower Road, Sliema SLM 1604, Malta', 'Malta', 'Sliema', 'EUR', 'il-gabbana'),
('Park Inn by Radisson Kigali', 'Avenue de Kiyovu & Res des Parcs Plot 5457, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'park-inn-by-radisson-kigali'),
('Bar Dolce', 'KN 35 St, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'bar-dolce'),
('Kigali Serena Hotel', 'KN 3 Ave, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'kigali-serena-hotel'),
('Giorgio''s', 'Tigné Seafront, Tas-Sliema, Malta', 'Malta', 'Tas-Sliema', 'EUR', 'giorgios'),
('Victoria Bar', 'X9Q4+Q67, Mellieħa, Malta', 'Malta', 'Mellieħa', 'EUR', 'victoria-bar'),
('Rosty Club', '24R6+65W, KG 18 Ave, Kigali, Rwanda', 'Malta', 'Kigali', 'EUR', 'rosty-club'),
('Bistro 516', '516 St. Paul Street, Valletta, Malta', 'Malta', 'Valletta', 'EUR', 'bistro-516-2'),
('Il Galeone', 'Triq IxXatt ta Tigne, Tas-Sliema, Malta', 'Malta', 'Tas-Sliema', 'EUR', 'il-galeone'),
('Bar Filao', '24P3+269, Kigali, Rwanda', 'Malta', 'Kigali', 'EUR', 'bar-filao'),
('Missed Call Pub', '23JJ+QJC, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'missed-call-pub'),
('Resto-Bar Chez John Maradona', '24J3+7QM, KK 19 Ave, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'resto-bar-chez-john-maradona'),
('Zizka', '42a West Street, Il-Belt Valletta, Malta', 'Malta', 'Valletta', 'EUR', 'zizka'),
('Tiffany''s Bistroc', 'c/t bisazza street, 88A Tigne Seafront, Tas-Sliema SLM 3010, Malta', 'Malta', 'Tas-Sliema', 'EUR', 'tiffanys-bistroc'),
('Nobleza Hotel', 'Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'nobleza-hotel'),
('Tortuga Malta', 'Little Armier Bay, Mellieħa MLH 5940, Malta', 'Malta', 'Mellieħa', 'EUR', 'tortuga-malta'),
('Felice Brasserie', 'Merchant Street, Valletta, Malta', 'Malta', 'Valletta', 'EUR', 'felice-brasserie-3'),
('Mamma Mia Restaurant', 'Ta'' Xbiex Seafront, Ta'' Xbiex XBX 1028, Malta', 'Malta', 'Ta'' Xbiex', 'EUR', 'mamma-mia-restaurant'),
('La Sfoglia', '67/68, triq Il-Merkanti, Il-Belt Valletta VLT 1175, Malta', 'Malta', 'Valletta', 'EUR', 'la-sfoglia'),
('The Black Sheep drink and dine', '55 Triq Ix - Xatt Tas-Sliema Sliema, Tas-Sliema SLM 1022, Malta', 'Malta', 'Tas-Sliema', 'EUR', 'the-black-sheep-drink-and-dine'),
('Port 21 Restaurant', 'ix-Xatt Ta'' Xbiex, Ta'' Xbiex, Malta', 'Malta', 'Ta'' Xbiex', 'EUR', 'port-21-restaurant'),
('Gozitan Restaurant', 'Triq Paceville, San Ġiljan, Malta', 'Malta', 'San Ġiljan', 'EUR', 'gozitan-restaurant'),
('Come Again. Kicukiro', 'KK 41 Ave, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'come-again-kicukiro'),
('Spinola Cafe Lounge St Julians', NULL, 'Malta', NULL, 'EUR', 'spinola-cafe-lounge-st-julians-2'),
('The Brew Bar Grill', NULL, 'Malta', NULL, 'EUR', 'the-brew-bar-grill-2'),
('Bellavia Ristorante Italiano', '63 Wilga St, St Julian''s, Malta', 'Malta', 'St Julian''s', 'EUR', 'bellavia-ristorante-italiano'),
('The Watson''s Pub & Diner', 'Triq Il-Merluzz, San Pawl il-Baħar, Malta', 'Malta', 'San Pawl il-Baħar', 'EUR', 'the-watsons-pub-diner'),
('Kigali Sport Bar', 'KG 651 St, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'kigali-sport-bar'),
('Salia Restaurant - Mellieha', 'Triq il-Marfa, Mellieha Bay, Il-Mellieħa MLH 9064, Malta', 'Malta', 'Mellieħa', 'EUR', 'salia-restaurant-mellieha'),
('The Long Hall Irish Pub', 'WFFQ+FRM, St George''s Road, St Julian''s, Malta', 'Malta', 'St Julian''s', 'EUR', 'the-long-hall-irish-pub'),
('Happy Park', '24G3+PVJ, Kigali, Rwanda', 'Rwanda', 'Kigali', 'RWF', 'happy-park')
ON CONFLICT (slug) DO NOTHING;

COMMIT;
