version: "3.9"
services:
  sip-webhook:
    build: ../../apps/sip-webhook
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      TWILIO_MEDIA_STREAM_WSS: ${TWILIO_MEDIA_STREAM_WSS}
      SIP_WEBHOOK_PORT: 3001
    ports:
      - "3001:3001"
  voice-bridge:
    build: ../../apps/voice-bridge
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_REALTIMEL_URL: ${OPENAI_REALTIMEL_URL}
      AGENT_DEFAULT_VOICE: ${AGENT_DEFAULT_VOICE}
      AGENT_VAD_PREFIX_MS: ${AGENT_VAD_PREFIX_MS}
      AGENT_VAD_SILENCE_MS: ${AGENT_VAD_SILENCE_MS}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      VOICE_BRIDGE_PORT: 8080
    ports:
      - "8080:8080"
  agent-core:
    build: ../../apps/agent-core
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_RESPONSES_MODEL: ${OPENAI_RESPONSES_MODEL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      AGENT_CORE_PORT: 3002
    ports:
      - "3002:3002"
