BEGIN;

-- ---------------------------------------------------------------------------
-- Deep link tokens bootstrap WhatsApp flows without full onboarding.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.deeplink_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token text NOT NULL UNIQUE,
  flow text NOT NULL,
  msisdn text,
  max_uses integer NOT NULL DEFAULT 1 CHECK (max_uses > 0),
  remaining_uses integer NOT NULL DEFAULT 1 CHECK (remaining_uses >= 0),
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CHECK (remaining_uses <= max_uses)
);

CREATE INDEX IF NOT EXISTS idx_deeplink_tokens_flow
  ON public.deeplink_tokens (flow);

CREATE INDEX IF NOT EXISTS idx_deeplink_tokens_expires
  ON public.deeplink_tokens (expires_at);

CREATE INDEX IF NOT EXISTS idx_deeplink_tokens_remaining
  ON public.deeplink_tokens (remaining_uses DESC)
  WHERE remaining_uses > 0;

CREATE OR REPLACE FUNCTION public.deeplink_tokens_set_remaining()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.remaining_uses IS NULL OR NEW.remaining_uses <= 0 THEN
      NEW.remaining_uses := NEW.max_uses;
    END IF;
  ELSE
    IF NEW.remaining_uses > NEW.max_uses THEN
      NEW.remaining_uses := NEW.max_uses;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_deeplink_tokens_remaining
  BEFORE INSERT OR UPDATE ON public.deeplink_tokens
  FOR EACH ROW EXECUTE FUNCTION public.deeplink_tokens_set_remaining();

CREATE TRIGGER trg_deeplink_tokens_touch
  BEFORE UPDATE ON public.deeplink_tokens
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Token events capture usage (scan, expired, redeemed, etc.)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.deeplink_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_id uuid NOT NULL REFERENCES public.deeplink_tokens(id) ON DELETE CASCADE,
  event text NOT NULL CHECK (event IN ('issued','opened','redeemed','expired','revoked')),
  context jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_deeplink_events_token
  ON public.deeplink_events (token_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_deeplink_events_event
  ON public.deeplink_events (event, created_at DESC);

COMMIT;
