# Copy this file to `.github/workflows/ci.yml` in the new repository.
# It runs linting, tests, a production build, and Supabase migration checks using the detected package manager on Node 18.
# Adjust the individual commands to match the scripts that exist in your package.json.

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
      SUPABASE_EDGE_FUNCTIONS_REGION: ${{ secrets.SUPABASE_EDGE_FUNCTIONS_REGION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect package manager
        id: pkg
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "manager=pnpm" >>"$GITHUB_OUTPUT"
            echo "install=pnpm install --frozen-lockfile" >>"$GITHUB_OUTPUT"
            echo "run=pnpm run" >>"$GITHUB_OUTPUT"
            echo "exec=pnpm exec" >>"$GITHUB_OUTPUT"
            echo "cache=pnpm" >>"$GITHUB_OUTPUT"
          elif [ -f yarn.lock ]; then
            echo "manager=yarn" >>"$GITHUB_OUTPUT"
            echo "install=yarn install --frozen-lockfile" >>"$GITHUB_OUTPUT"
            echo "run=yarn" >>"$GITHUB_OUTPUT"
            echo "exec=yarn" >>"$GITHUB_OUTPUT"
            echo "cache=yarn" >>"$GITHUB_OUTPUT"
          else
            echo "manager=npm" >>"$GITHUB_OUTPUT"
            echo "install=npm ci" >>"$GITHUB_OUTPUT"
            echo "run=npm run" >>"$GITHUB_OUTPUT"
            echo "exec=npx" >>"$GITHUB_OUTPUT"
            echo "cache=npm" >>"$GITHUB_OUTPUT"
          fi

      - name: Set up PNPM
        if: steps.pkg.outputs.manager == 'pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Enable Corepack
        if: steps.pkg.outputs.manager != 'pnpm'
        run: corepack enable

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: ${{ steps.pkg.outputs.cache }}

      - name: Install dependencies
        run: ${{ steps.pkg.outputs.install }}

      - name: Lint
        run: |
          if node -e "const pkg=require('./package.json'); process.exit(pkg.scripts?.lint ? 0 : 1)"; then
            ${{ steps.pkg.outputs.run }} lint
          else
            echo "No lint script defined; skipping."
          fi

      - name: Run unit tests
        run: |
          if node -e "const pkg=require('./package.json'); process.exit(pkg.scripts?.test ? 0 : 1)"; then
            ${{ steps.pkg.outputs.run }} test -- --passWithNoTests
          else
            echo "No test script defined; skipping."
          fi

      - name: Build Next.js application
        run: ${{ steps.pkg.outputs.run }} build

      - name: Upload build artifact (optional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next
          if-no-files-found: ignore

  verify-migrations:
    # Runs Supabase migration checks separately to keep feedback clear even if the build fails.
    runs-on: ubuntu-latest
    needs: install-and-test
    if: ${{ always() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect package manager
        id: pkg
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "manager=pnpm" >>"$GITHUB_OUTPUT"
            echo "install=pnpm install --frozen-lockfile" >>"$GITHUB_OUTPUT"
            echo "exec=pnpm exec" >>"$GITHUB_OUTPUT"
            echo "cache=pnpm" >>"$GITHUB_OUTPUT"
          elif [ -f yarn.lock ]; then
            echo "manager=yarn" >>"$GITHUB_OUTPUT"
            echo "install=yarn install --frozen-lockfile" >>"$GITHUB_OUTPUT"
            echo "exec=yarn" >>"$GITHUB_OUTPUT"
            echo "cache=yarn" >>"$GITHUB_OUTPUT"
          else
            echo "manager=npm" >>"$GITHUB_OUTPUT"
            echo "install=npm ci" >>"$GITHUB_OUTPUT"
            echo "exec=npx" >>"$GITHUB_OUTPUT"
            echo "cache=npm" >>"$GITHUB_OUTPUT"
          fi

      - name: Set up PNPM (required for Supabase CLI via devDependencies)
        if: steps.pkg.outputs.manager == 'pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Enable Corepack
        if: steps.pkg.outputs.manager != 'pnpm'
        run: corepack enable

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: ${{ steps.pkg.outputs.cache }}

      - name: Install Supabase CLI dependencies
        run: ${{ steps.pkg.outputs.install }}

      - name: Validate Supabase migrations
        # Swap this command for `pnpm supabase db push --dry-run` if you
        # maintain a script alias in package.json.
        run: ${{ steps.pkg.outputs.exec }} supabase db lint
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
