#!/bin/bash
# Enable AI Agents via Supabase Dashboard
# Due to 100 secret limit, use a consolidated flag

echo "============================================"
echo "AI Agents Activation Guide"
echo "============================================"
echo ""
echo "Your Supabase project has reached the 100 secret limit."
echo "You have two options to enable AI agents:"
echo ""
echo "OPTION 1: Use Supabase Dashboard (Recommended)"
echo "  1. Go to: https://supabase.com/dashboard/project/lhbowpbcpwoiparwnwgt/settings/edge-functions"
echo "  2. Add these secrets:"
echo "     FEATURE_AGENT_NEARBY_DRIVERS = true"
echo "     FEATURE_AGENT_PHARMACY = true"
echo "     FEATURE_AGENT_PROPERTY_RENTAL = true"
echo "     FEATURE_AGENT_SCHEDULE_TRIP = true"
echo "     FEATURE_AGENT_SHOPS = true"
echo "     FEATURE_AGENT_QUINCAILLERIE = true"
echo ""
echo "OPTION 2: Use Consolidated Flag (Alternative)"
echo "  Set a single flag to enable multiple agents:"
echo "     FEATURE_AGENT_ALL = true"
echo "     (Requires code modification to check this flag)"
echo ""
echo "OPTION 3: Remove Unused Secrets"
echo "  Review existing secrets and remove any that are no longer needed:"
echo "     supabase secrets list"
echo "     supabase secrets unset SECRET_NAME"
echo ""
echo "Current secret count: $(supabase secrets list | wc -l) / 100"
echo ""
echo "============================================"
