import { InsurerProfile } from "./types";

export const INSURER_PROFILES: Record<string, InsurerProfile> = {
  "BK Insurance": {
    providerName: "BK Insurance",
    slug: "bk",
    legalName: "BK General Insurance Rwanda Plc",
    momoMerchantCode: "000123",
    momoReferencePrefix: "BK",
    momoChannelDescription: "BK | Motor premiums",
    supportPhone: "+250788123000",
    supportEmail: "support@bkinsurance.rw",
    claimsEmail: "claims@bkinsurance.rw",
    headOfficeAddress: "KN 4 Ave, Kigali",
    notes: ["COMESA handled on same merchant code."],
  },
  "Old Mutual Rwanda": {
    providerName: "Old Mutual Rwanda",
    slug: "old-mutual",
    legalName: "Old Mutual Insurance Rwanda Ltd",
    momoMerchantCode: "000245",
    momoReferencePrefix: "OM",
    momoChannelDescription: "Old Mutual | Motor premiums",
    supportPhone: "+250788222555",
    supportEmail: "clientservice@oldmutual.rw",
    claimsEmail: "claims@oldmutual.rw",
    headOfficeAddress: "KG 7 Ave, Kigali",
    notes: ["Corporate and individual MoMo wallet share the same code."],
  },
  "Prime Insurance": {
    providerName: "Prime Insurance",
    slug: "prime",
    legalName: "Prime Life & General Insurance Rwanda",
    momoMerchantCode: "000377",
    momoReferencePrefix: "PR",
    momoChannelDescription: "Prime Insurance | Motor",
    supportPhone: "+250788334455",
    supportEmail: "care@prime.rw",
    claimsEmail: "claims@prime.rw",
    headOfficeAddress: "KN 5 Rd, Kigali",
    notes: ["Use Glass extension add-on sheet if needed."],
  },
  "Radiant Insurance": {
    providerName: "Radiant Insurance",
    slug: "radiant",
    legalName: "Radiant Insurance Company Ltd",
    momoMerchantCode: "000498",
    momoReferencePrefix: "RD",
    momoChannelDescription: "Radiant | Motor premiums",
    supportPhone: "+250788556677",
    supportEmail: "info@radiant.rw",
    claimsEmail: "claims@radiant.rw",
    headOfficeAddress: "KG 9 Ave, Kigali",
    notes: ["Corporate vs individual TP bases configured in pricing engine."],
  },
};
