#!/bin/bash
# Scrape 10,000+ businesses in Kigali with phone numbers

set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Scraping 10,000+ Kigali Businesses with Phone Numbers    ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Set environment
export SUPABASE_URL="https://lhbowpbcpwoiparwnwgt.supabase.co"
export SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxoYm93cGJjcHdvaXBhcndud2d0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDU1ODEyNywiZXhwIjoyMDc2MTM0MTI3fQ.mcL3A7LLsyo7Y45hnBXLAYCbp7FpEAfXVRrZoC4CWqc"

# Extended category list for 10k+ businesses
CATEGORIES=(
    "pharmacy"
    "restaurant"
    "hotel"
    "hospital"
    "clinic"
    "supermarket"
    "gas station"
    "bank"
    "atm"
    "cafe"
    "bar"
    "bakery"
    "butcher"
    "salon"
    "barbershop"
    "spa"
    "gym"
    "school"
    "university"
    "church"
    "mosque"
    "police"
    "post office"
    "library"
    "museum"
    "theater"
    "cinema"
    "parking"
    "car wash"
    "car repair"
    "mechanic"
    "electronics store"
    "phone shop"
    "bookstore"
    "clothing store"
    "shoe store"
    "jewelry store"
    "furniture store"
    "hardware store"
    "paint store"
    "laundry"
    "dry cleaner"
    "dentist"
    "veterinary"
    "pet store"
    "mall"
    "market"
    "grocery store"
    "convenience store"
    "liquor store"
    "florist"
    "real estate"
    "lawyer"
    "accounting"
    "insurance"
    "travel agency"
    "printing"
    "construction"
    "plumber"
    "electrician"
    "carpenter"
    "painter"
    "roofing"
    "locksmith"
    "storage"
    "moving company"
    "taxi"
    "bus station"
    "airport"
    "nightclub"
    "sports club"
    "stadium"
    "golf course"
    "swimming pool"
    "park"
    "zoo"
    "aquarium"
)

echo "Total categories: ${#CATEGORIES[@]}"
echo "Target: 10,000+ businesses with phone numbers"
echo "City: Kigali, Rwanda"
echo ""
echo "Starting in 5 seconds... (Ctrl+C to cancel)"
sleep 5

# Run scraper
python3 google_maps_bulk_scraper.py \
    --categories "${CATEGORIES[@]}" \
    --cities "Kigali" \
    --per-category-limit 200 \
    --delay 3

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Scraping Complete!                                        ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Results saved to: scraper_results/"
echo ""
echo "To check results:"
echo "  cat scraper_results/bulk_summary_*.json | jq '.'"
echo ""
echo "To verify in Supabase:"
echo "  SELECT category, COUNT(*) FROM businesses WHERE city='Kigali' AND phone IS NOT NULL GROUP BY category;"
echo ""
