// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezrriefbmhiiqfoxgjgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6cnJpZWZibWhpaXFmb3hnamd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzkzNjEsImV4cCI6MjA3MjgxNTM2MX0.xl0dmH6vm-sM-rqfN_E4HR3aapLf57eFCXrXG6UBsO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});