name: OpenAPI Lint

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  lint-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Lint apispec/openapi.yaml (if present)
        if: ${{ hashFiles('apispec/openapi.yaml') != '' }}
        run: npx -y @redocly/cli@latest lint apispec/openapi.yaml
        continue-on-error: true
      - name: Lint public/openapi.yaml (if present)
        if: ${{ hashFiles('public/openapi.yaml') != '' }}
        run: npx -y @redocly/cli@latest lint public/openapi.yaml
        continue-on-error: true
      - name: Lint admin-app/public/openapi.yaml (if present)
        if: ${{ hashFiles('admin-app/public/openapi.yaml') != '' }}
        run: npx -y @redocly/cli@latest lint admin-app/public/openapi.yaml
        continue-on-error: true
      - name: No OpenAPI specs found
        if: ${{ !(hashFiles('apispec/openapi.yaml') != '' || hashFiles('public/openapi.yaml') != '' || hashFiles('admin-app/public/openapi.yaml') != '') }}
        run: echo "No OpenAPI specs found; skipping lint."
