name: Vercel Deploy Hook

on:
  push:
    branches: [ main ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        env:
          HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "${HOOK}" ]; then
            echo "VERCEL_DEPLOY_HOOK_URL secret not set; skipping." >&2
            exit 0
          fi
          curl -fsSL -X POST "${HOOK}" -H 'Content-Type: application/json' -d '{}' && echo 'OK'

